(add-to-list 'load-path "~/.emacs.d/includes/color-theme-6.6.0")
 (require 'color-theme)
 (setq color-theme-is-global t)
 (color-theme-initialize)
 ;; A nice dark color theme
 (color-theme-deep-blue)
(setq longlines-wrap-follows-window-size t)
(global-set-key [(control meta l)] 'longlines-mode)
(setq word-wrap t) (setq visual-line-indicators (quote (nil nil))
(setq line-move-visual nil)
(add-hook 'lisp-mode-hook '(lambda ()(local-set-key (kbd "RET") 'newline-and-indent)))
(set q global-linum-mode t)
 (defun clear-shell ()
   (interactive)
   (let ((old-max comint-buffer-maximum-size))
     (setq comint-buffer-maximum-size 0)
     (comint-truncate-buffer)
     (setq comint-buffer-maximum-size old-max)))